return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "c_sharp",
      "css",
      "dart",
      "dockerfile",
      "dot",
      "fish",
      "gitignore",
      "go",
      "graphql",
      "html",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "markdown",
      "php",
      "prisma",
      "python",
      "rust",
      "scss",
      "sql",
      "svelte",
      "tsx",
      "typescript",
      "vue",
      "yaml",
      "zig",
    },
  },
}
