return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "yaml",
      -- "dockerfile",
      -- "go",
      -- "json",
      -- "jsonc",
      -- "javascript",
      -- "typescript",
      -- "markdown",
      -- "php",
      -- "prisma",
      -- "python",
      -- "sql",
      -- "svelte",
      -- "css",
      -- "scss",
      -- "vue",
      -- "c_sharp",
      -- "rust",
      -- "html",
      -- "graphql",
      -- "zig",
      -- "fish",
      -- "tsx",
      -- "dart",
      -- "gitignore",
      -- "dot",
    },
  },
}
